spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/homework40
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bestuser
    password: bestuser
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update